// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqURT9gulLqe4hj6DSq71PljwdQ7YimuE',
    appId: '1:1093212011499:web:32901e83463234814bb7ae',
    messagingSenderId: '1093212011499',
    projectId: 'skatespotfinder-22c5b',
    authDomain: 'skatespotfinder-22c5b.firebaseapp.com',
    storageBucket: 'skatespotfinder-22c5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaIzfaIG6SETakAg6SU4iwHfFhvIAmDw',
    appId: '1:1093212011499:android:6328379ba6eb24744bb7ae',
    messagingSenderId: '1093212011499',
    projectId: 'skatespotfinder-22c5b',
    storageBucket: 'skatespotfinder-22c5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATmpGOsS4kjIr_r-fl0F5eMpCqalOcF5U',
    appId: '1:1093212011499:ios:7b95ee9b717e75e54bb7ae',
    messagingSenderId: '1093212011499',
    projectId: 'skatespotfinder-22c5b',
    storageBucket: 'skatespotfinder-22c5b.appspot.com',
    iosBundleId: 'com.dominikgrosser.skatewars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATmpGOsS4kjIr_r-fl0F5eMpCqalOcF5U',
    appId: '1:1093212011499:ios:6227a3874117887c4bb7ae',
    messagingSenderId: '1093212011499',
    projectId: 'skatespotfinder-22c5b',
    storageBucket: 'skatespotfinder-22c5b.appspot.com',
    iosBundleId: 'com.dominikgrosser.skatewars.RunnerTests',
  );
}
